### ISSUE TITLE
ChromeDriver only supports Chrome version 74

### ISSUE THREAD

**Issue by jankeesvw** [richardvenneman/instagrammer#3]
Yesterday I did a deployment of this gem in production and I noticed this error when someone tries to fetch an Instagram feed:

> session not created: This version of ChromeDriver only supports Chrome version 74 (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-54-generic x86_64) 

Is this a know issue? I'm running it with Dokku (should be similar to Heroku)

**Comment by richardvenneman** [comment]
@jankeesvw thanks for reporting this issue, I've seen similar errors coming in.

✅ I just released version 0.3.0 which should address this.

**Comment by jankeesvw** [comment]
Great, thanks @richardvenneman. I just deployed this new version and it seems to work!  ✨ 

Btw I'm using instagrammer in https://rssmailer.app in case you are wondering.

**Comment by richardvenneman** [comment]
Nice! Glad to hear it's of use to you in your project :)
